language: php

php:
  - 7.1.3
  - 7.2

env:
  global:
    - setup=basic

matrix:
  fast_finish: true

sudo: false

services:
  - memcached
  - redis-server

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi

script:
  - >
    if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then
      phpdbg -qrr vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover --coverage-text;
    else
      vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --coverage-clover=coverage.clover
    fi

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --access-token="9857f9bb4b1c260b94eb773a541d6e42e05db0db45d5a25757590276d5e50445" --format=php-clover coverage.clover

notifications:
  slack: big-boss-studio:vLrsJ3hpqgIYugU7IKLMUwj2
